### ISSUE TITLE
Special character produce invalid manifest.xml

### ISSUE THREAD

**Issue by britter** [codecentric/gradle-opencms-plugin#1]
If the nice name of a feature contains special letters (like Ö,Ä,Ü), the generated manifest.xml file will be invalid. Looks like system encoding is not taken into account.

**Comment by rbutenuth** [comment]
Bug is probably in CmsManifestTask.groovy, line 113:
 manifestFile.text = '<?xml version="1.0" encoding="UTF-8"?>\n' + writer.toString()

replace with

 manifestFile.write('<?xml version="1.0" encoding="UTF-8"?>\n' + writer.toString(), 'UTF-8')

**Comment by weltraumpirat** [comment]
How about you guys fix it and submit a pull request?

**Comment by rbutenuth** [comment]
Fixed in version 2.1-SNAPSHOT
